import { Document, Types } from "mongoose";

import { RolesEnum } from "./RolesEnum";
import { ICollection } from "./interfaces/CollectionInterface";
import { FileInterface } from "./FileInterface";

export interface UserInterface extends Document {
  firstName: string;
  lastName: string;
  fullName: string;
  userName: string;
  phoneNumber: string;
  email: string;
  password: string;
  googleId?: string | null;
  role: RolesEnum;
  isMentor?: boolean;
  mentorExpertise?: string[];
  mentorCertifications?: string[];
  mentorYearsExperience?: number | null;
  mentorHasFreeTrial?: boolean;
  mentorRating?: number | null;
  mentorReviewCount?: number;
  mentorAiVoiceTone?: string;
  mentorAiKnowledgeBaseFileIds?: Types.ObjectId[];
  mentorAiTrainingPhilosophy?: string;
  mentorAiNutritionPhilosophy?: string;
  mentorAiMacroApproach?: string;
  mentorAiDietaryNotes?: string;
  coreInstructions?: string;
  lastLogin: Date;
  photoId: Types.ObjectId | FileInterface;
  coverPhotoId: Types.ObjectId | FileInterface;
  country: string;
  dialCode: string;
  instagramLink: string;
  facebookLink: string;
  tiktokLink: string;
  youtubeLink: string;
  isVerified: boolean;
  verifiedAt?: Date | null;
  verifiedBy?: string | null;
  hasPersonalInfo?: boolean;
  hasPhotoInfo?: boolean;
  hasConfirmedAge?: boolean;
  stripeProductId: string;
  stripeProduct: {} | any;
  hasSelectedInterest?: boolean;
  hasDocumentUploaded?: boolean;
  hasDocumentVerified?: boolean;
  interests: Types.ObjectId[];
  isStripeCustomer: string;
  stripeClientId: string;
  fcm_token: string;
  loginAttempts?: number;
  lockUntil?: Date | null;
  isActive: boolean;
  activatedAt: Date;
  isDeleted: boolean;
  deletedAt: Date;
  otp: string;
  otpInvalidAt: Date;
  isFreeSubscription: Boolean;
  primaryCollection: Types.ObjectId | ICollection;
}
