export enum InteractionType {
  LIKE_POST = "LIKE_POST",
  LIKE_STORY = "LIKE_STORY",
  COMMENT = "COMMENT",
  LIKE_COMMENT = "LIKE_COMMENT",
  COLLECTION_SAVED = "COLLECTION_SAVED",
  IMPRESSION = "IMPRESSION",
  VIEW = "VIEW",
}
